### ISSUE TITLE
named object access in object collections

### ISSUE THREAD

**Issue by buhman** [spotify/ramlfications#100]
In raml that looks like this:

```yaml
post:
  body:
    application/json:
      schema: !include foo.json
```

When traversing that resource in the raw raml, a response type could be accessed like this:

```python
mime_type = node['body']['application/json']
```

In the representation in ramlfications, equivalent access would look like this:

```python
mime_type = [m for m in node.body if m.mime_type == 'application/json'][0]
```

This also applies to pretty much anything, including `RootNode.resources`. 

What do you think about changing the pattern to something like:

```python
{
  'application/json': Body()
}
```
