### ISSUE TITLE
Bugs while parsing trait.

### ISSUE THREAD

**Issue by triStone** [spotify/ramlfications#103]
I have a trait file like below.

``` yaml
traits:
  paging:
    queryParameters:
      page_size:
        description: the amount of elements of each result page
        type: integer
        required: false
        example: 10
      page_no:
        description: the page number
        type: integer
        required: false
        example: 0
```

RAMLfications can not parse this raml file correctly. I've track the code in `parser.py` and `validata.py`. And think these code in `parser.py:371` should be changed to

``` python
for trait in traits:
        name = trait
        data = traits[name]
        trait_objects.append(wrap(name, data))
```

And the code in `validate.py:189` should be changed to

``` python
trait_names = [name for name in traits]
```

BTW: My Python version is 3.5, and I haven't check if this bug existed in Python2
