### ISSUE TITLE
queryParameters and formParameters formats are inconsistent

### ISSUE THREAD

**Issue by johnlinp** [spotify/ramlfications#122]
In the following RAML:

```
/some/api:
  get:
    queryParameters:
      some_query_string:
        type: string
        required: true
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          some_form_string:
            required: true
            type: string
```

I was excepting that `query_params` and `form_params` are in the same format since they are in similar structure. However, `query_params` is a `list` of `QueryParameter`, while `form_params` is a `OrderedDict` with parameter names as the keys.

Is there any change to make them consistent?
