### ISSUE TITLE
How to inherit resourceTypes by resource?

### ISSUE THREAD

**Issue by postatum** [spotify/ramlfications#23]
Hi guys.
First of all, thanks a lot for all you work. Enjoying your parser a lot so far.

When working with resourceTypes I've faced an issue: How do I make resource inherit from one of resourceTypes properly in ramlfications?

[Docs section says](https://ramlfications.readthedocs.org/en/latest/extendedusage.html#mapping-of-properties-and-elements-from-traits-resource-types-to-resources) that 
> When a resource has a trait and/or type assigned to it, or a resource type has another resource type or a trait assigned to it, it inherits its properties.

I have following RAML file:

```
#%RAML 0.8
---
title: Example REST API
documentation:
    - title: Home
      content: Welcome to the example API.
baseUri: http://example.com
version: v1
resourceTypes:
    - collection:
        description: The collection of items
        get:
            description: Get all items, optionally filtered
        post:
            description: Create a new items object

/items:
    type: collection
```

What I expect after parsing this file is:
* 1 /items resource with method GET
* 1 /items resource with method POST
* Both resources having proper descriptions
* /items resources having proper resource description (The collection of items)

But when I parse it and check results in console, that's what I see:

```
In [1]: import ramlfications

In [2]: api = ramlfications.parse('example.raml')

In [3]: api.resources
Out[3]: [ResourceNode(method=None, path='/items')]

In [4]: resource = api.resources[0]

In [5]: resource.description
Out[5]: ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
.......
TypeError: __repr__ returned non-string (type NoneType)
```

I tried defining methods on /items route as follows and was hoping inheritance will have this way but had no luck again.
```
...
/items:
    type: collection
    get:
    post:
```

Please give an advice on what is the correct way to achieve what I want using ramlfications?

Thanks for your time! :)
